version: "3.9"

services:
  backend:
    container_name: spectre-backend
    build:
      context: ../../..
      dockerfile: deploy/docker/backend/Dockerfile.backend
    env_file:
      - ../../../.env
    environment:
      REDIS_URL: ${REDIS_URL}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_TIMEOUT_SECONDS: ${CLICKHOUSE_TIMEOUT_SECONDS}
    ports:
      - "8000:8000"
    networks:
      - redis
      - clickhouse

networks:
  redis:
    external: true
    name: redis_default
  clickhouse:
    external: true
    name: clickhouse_default
