FROM python:3.13-slim

WORKDIR /app

# Instalar dependencias
COPY backend/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copiar codigo fuente
COPY shared /app/shared
COPY backend /app/backend

ENV PYTHONPATH=/app

# En dev, usamos reload. En prod, quitar reload.
CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
